/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.penggajian.main;

import com.penggajian.view.AturTunjanganKeluargaDanPanganDialog;
import com.penggajian.view.BuatLaporanPenggajianBulananDialog;
import com.penggajian.view.BuatLaporanRincianHonorBulananDialog;
import com.penggajian.view.DaftarDataPegawaiView;
import com.penggajian.view.DaftarPokokHonorView;
import com.penggajian.view.DaftarTransaksiPenggajianPerUnitKerjaView;
import com.penggajian.view.DaftarTunjanganFungsionalDialog;
import com.penggajian.view.DaftarTunjanganKelebihanJamMengajarDialog;
import com.penggajian.view.DaftarTunjanganKhususDialog;
import com.penggajian.view.DaftarTunjanganStaffKurikulumEkstraKurikuluerDialog;
import com.penggajian.view.DaftarTunjanganYayasanDialog;
import com.penggajian.view.TabelDaftarGajiPokokView;
import com.penggajian.view.TabelDaftarTunjanganJabatanDialog;

/**
 *
 * @author Windows
 */
public class MainView extends javax.swing.JFrame {

    private DaftarDataPegawaiView daftarDataPegawaiView;
    private static MainView instance;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setLocationRelativeTo(this);
        //setExtendedState(MAXIMIZED_BOTH);

    }

    public static MainView getInstance() {
        return instance;
    }

    public DaftarDataPegawaiView getDaftarDataPegawaiView() {
        return daftarDataPegawaiView;
    }

    public void setDaftarDataPegawaiView(DaftarDataPegawaiView daftarDataPegawaiView) {
        this.daftarDataPegawaiView = daftarDataPegawaiView;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDataPegawai = new javax.swing.JMenuItem();
        menuPokokHonor = new javax.swing.JMenuItem();
        menuTabelGajiPokok = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuTunjanganJabatan = new javax.swing.JMenuItem();
        menuTunjanganFungsional = new javax.swing.JMenuItem();
        menuTunjanganKelebihanJamMengajar = new javax.swing.JMenuItem();
        menuTunjanganStafKurikulerEkstrakurikuluer = new javax.swing.JMenuItem();
        menuTunjanganKhusus = new javax.swing.JMenuItem();
        menuTunjanganKeluargaNPangan = new javax.swing.JMenuItem();
        menuTunjanganYaysan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuTransaksiPenggajian = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuLaporanPenggajianBulanan = new javax.swing.JMenuItem();
        menuLaporanRincianHonor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:Sistem Penggajian Pegawai Mardi Yuana");
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );

        jMenu1.setText("Aplikasi");

        menuKeluar.setText("Keluar Aplikasi");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu1.add(menuKeluar);

        menubar.add(jMenu1);

        jMenu2.setText("Master");

        menuDataPegawai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuDataPegawai.setText("Data Pegawai");
        menuDataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu2.add(menuDataPegawai);

        menuPokokHonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuPokokHonor.setText("Pokok Honor");
        menuPokokHonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu2.add(menuPokokHonor);

        menuTabelGajiPokok.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menuTabelGajiPokok.setText("Tabel Gaji Pokok");
        menuTabelGajiPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu2.add(menuTabelGajiPokok);

        jMenu4.setText("Tunjangan");

        menuTunjanganJabatan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menuTunjanganJabatan.setText("Tabel Tunjangan Jabatan");
        menuTunjanganJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu4.add(menuTunjanganJabatan);

        menuTunjanganFungsional.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuTunjanganFungsional.setText("Tunjangan Fungsional");
        menuTunjanganFungsional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu4.add(menuTunjanganFungsional);

        menuTunjanganKelebihanJamMengajar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuTunjanganKelebihanJamMengajar.setText("Tunjangan Kelebihan Jam Mengajar");
        menuTunjanganKelebihanJamMengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu4.add(menuTunjanganKelebihanJamMengajar);

        menuTunjanganStafKurikulerEkstrakurikuluer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuTunjanganStafKurikulerEkstrakurikuluer.setText("Tunjangan Staf/Kurikuler/Ekstrakurikuluer");
        menuTunjanganStafKurikulerEkstrakurikuluer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu4.add(menuTunjanganStafKurikulerEkstrakurikuluer);

        menuTunjanganKhusus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        menuTunjanganKhusus.setText("Tunjangan Khusus");
        menuTunjanganKhusus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu4.add(menuTunjanganKhusus);

        menuTunjanganKeluargaNPangan.setText("Tunjangan Keluarga dan Pangan");
        menuTunjanganKeluargaNPangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu4.add(menuTunjanganKeluargaNPangan);

        menuTunjanganYaysan.setText("Tunjangan Yayasan");
        menuTunjanganYaysan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu4.add(menuTunjanganYaysan);

        jMenu2.add(jMenu4);

        menubar.add(jMenu2);

        jMenu3.setText("Transaksi");

        menuTransaksiPenggajian.setText("Transaksi Penggajian");
        menuTransaksiPenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu3.add(menuTransaksiPenggajian);

        menubar.add(jMenu3);

        jMenu5.setText("Laporan");

        menuLaporanPenggajianBulanan.setText("Laporan Penggajian Bulanan");
        menuLaporanPenggajianBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu5.add(menuLaporanPenggajianBulanan);

        menuLaporanRincianHonor.setText("Laporan Rincian Honor");
        menuLaporanRincianHonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionMenuItem(evt);
            }
        });
        jMenu5.add(menuLaporanRincianHonor);

        menubar.add(jMenu5);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionMenuItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionMenuItem
        // TODO add your handling code here:
        Object source = evt.getSource();
        if (source == menuDataPegawai) {
            showView(new DaftarDataPegawaiView(this));
        } else if(source == menuTransaksiPenggajian) {
            showView(new DaftarTransaksiPenggajianPerUnitKerjaView(this));
        } else if(source == menuPokokHonor) {
            showView(new DaftarPokokHonorView(this));
        } else if(source == menuTabelGajiPokok) {
            showView(new TabelDaftarGajiPokokView(this));
        } else if(source == menuTunjanganJabatan) {
            showView(new TabelDaftarTunjanganJabatanDialog(this));
        } else if(source == menuTunjanganFungsional) {
            showView(new DaftarTunjanganFungsionalDialog(this));
        } else if(source == menuTunjanganKelebihanJamMengajar) {
            showView(new DaftarTunjanganKelebihanJamMengajarDialog(this));
        } else if(source == menuTunjanganStafKurikulerEkstrakurikuluer) {
            showView(new DaftarTunjanganStaffKurikulumEkstraKurikuluerDialog(this));
        } else if(source == menuTunjanganKhusus) {
            showView(new DaftarTunjanganKhususDialog(this));
        } else if(source == menuTunjanganKeluargaNPangan) {
            showView(new AturTunjanganKeluargaDanPanganDialog(this));
        } else if(source == menuLaporanPenggajianBulanan) {
            showView(new BuatLaporanPenggajianBulananDialog(this));
        } else if(source == menuTunjanganYaysan) {
            showView(new DaftarTunjanganYayasanDialog(this));
        } else if(source == menuLaporanRincianHonor) {
            showView(new BuatLaporanRincianHonorBulananDialog(this));
        } else if(source == menuKeluar) {
            System.exit(0);
        }
    }//GEN-LAST:event_actionMenuItem

    /**
     * @param args the command line arguments
     */
    /*private static MasterService masterService;

    public static MasterService getMasterService() {
        return masterService;
    }
    
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("spring.xml");
        masterService = (MasterService)applicationContext.getBean("masterService");
        
        List<PokokHonor> listmMasterPegawai = masterService.getAllPokokHonor();
       
        for (PokokHonor masterPegawai : listmMasterPegawai) {
            System.out.println("Nama : "+masterPegawai.getStatusKepegawaian()+", NIP : "+masterPegawai.getPendidikan());
        }
        
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(() -> {
            new MainView().setVisible(true);
        });*/
        
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem menuDataPegawai;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuLaporanPenggajianBulanan;
    private javax.swing.JMenuItem menuLaporanRincianHonor;
    private javax.swing.JMenuItem menuPokokHonor;
    private javax.swing.JMenuItem menuTabelGajiPokok;
    private javax.swing.JMenuItem menuTransaksiPenggajian;
    private javax.swing.JMenuItem menuTunjanganFungsional;
    private javax.swing.JMenuItem menuTunjanganJabatan;
    private javax.swing.JMenuItem menuTunjanganKelebihanJamMengajar;
    private javax.swing.JMenuItem menuTunjanganKeluargaNPangan;
    private javax.swing.JMenuItem menuTunjanganKhusus;
    private javax.swing.JMenuItem menuTunjanganStafKurikulerEkstrakurikuluer;
    private javax.swing.JMenuItem menuTunjanganYaysan;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration//GEN-END:variables

    public void showView(DialogView view){
        showView(view, null);
    }
    
    public void showView(DialogView view, Object parameter){
        view.display(this, parameter);
    }
    
}
