/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.penggajian.view;

import com.penggajian.main.DialogView;
import com.penggajian.main.MainView;
import com.penggajian.main.SpringManager;
import com.penggajian.service.MasterService;
import java.awt.Window;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import org.hibernate.SessionFactory;
import org.hibernate.classic.Session;
import org.hibernate.jdbc.Work;

/**
 *
 * @author echo
 */
public class BuatLaporanPenggajianBulananDialog extends DialogView {

    public BuatLaporanPenggajianBulananDialog(MainView formApp) {
        super(formApp);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tanggalLaporan = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBuatLaporan = new javax.swing.JButton();
        jButtonTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel1.setText("Laporan Penggajian");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tanggal Penggajian"));

        tanggalLaporan.setDate(new Date());
        tanggalLaporan.setDateFormatString("dd MMMM yyyy");

        jLabel2.setText("Tanggal Penggajian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tanggalLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tanggalLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButtonBuatLaporan.setText("Buat Laporan");
        jButtonBuatLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuatLaporanActionPerformed(evt);
            }
        });

        jButtonTutup.setText("Tutup");
        jButtonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuatLaporan)
                        .addGap(5, 5, 5)
                        .addComponent(jButtonTutup))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonBuatLaporan)
                        .addComponent(jButtonTutup)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTutupActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonTutupActionPerformed

    private void jButtonBuatLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuatLaporanActionPerformed
        Date date;
        date = tanggalLaporan.getDate();
        
        /*SessionFactory sessionFactory = SpringManager.getInstance().getBean(SessionFactory.class);
        Session session = sessionFactory.openSession();
        session.doWork(new Work() {

            @Override
            public void execute(Connection connection) throws SQLException {
                try {
                    //InputStream inputStream = DaftarTransaksiPenggajianPerUnitKerjaView.class.getResourceAsStream("/report/LaporanPenggajian.jasper");
                    //String inputStream = "./report/LaporanPenggajian.jasper";

                    Map<String, Object> map = new HashMap<>();
                    map.put("date", date);
                    map.put(JRParameter.REPORT_CONNECTION, connection);
                    map.put(JRParameter.REPORT_LOCALE, new Locale("in", "ID"));

        //InputStream jasperStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("com/penggajian/LaporanPenggajian.jasper");
        //JasperReport report = (JasperReport) JRLoader.loadObject(jasperStream);            
                    
        JasperReport report = (JasperReport) JRLoader.loadObject(new File("./report/LaporanPenggajian.jasper"));
        
                    //JasperPrint print = JasperFillManager.fillReport(inputStream, map);
        JasperPrint print = JasperFillManager.fillReport(report, map);
                    //JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream("/report/LaporanPenggajian.jasper"), map);
                    //JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream("D:/DATAKU/SEMESTER III/PEMROGRAMAN JAVA/SistemPenggajianPegawaiMardiYuana - Copy/src/LaporanPenggajian.jasper"), map);
                    //JasperViewer.viewReport(jp, false);

                    //JasperViewer viewer = new JasperViewer(print, false);
                    //viewer.setFitPageZoomRatio();
                    //viewer.setVisible(true);
                    //viewer.setAlwaysOnTop(true);
                    //JasperViewer.setDefaultLookAndFeelDecorated(true);
                    CetakLaporanView view = new CetakLaporanView(getMainView(), print);
                    view.display(BuatLaporanPenggajianBulananDialog.this, null);
                } catch (JRException ex) {
                    Logger.getLogger(BuatLaporanPenggajianBulananDialog.class.getName()).log(Level.SEVERE, null, ex);
                    //JOptionPane.showMessageDialog(BuatLaporanPenggajianBulananDialog.this, ex);
                }
            }
        });
        session.close();*/
        
        MasterService masterService = SpringManager.getInstance().getBean(MasterService.class);
        JasperPrint print = masterService.getLaporanPenggajianPegawaiBulanan(date);
        CetakLaporanView view = new CetakLaporanView(getMainView(), print);
        view.display(BuatLaporanPenggajianBulananDialog.this, null);
    }//GEN-LAST:event_jButtonBuatLaporanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuatLaporan;
    private javax.swing.JButton jButtonTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser tanggalLaporan;
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(Window formApp, Object parameter) {
        setLocationRelativeTo(formApp);
        setVisible(true);
    }
}
