/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.penggajian.view;

import com.penggajian.entity.DetailPerincianHonor;
import com.penggajian.entity.MasterPegawai;
import com.penggajian.entity.PokokHonor;
import com.penggajian.entity.TabelTunjanganJabatan;
import com.penggajian.entity.TransaksiPenggajianPegawai;
import com.penggajian.entity.TunjanganStaffKurikulumEkstrakurikuluer;
import com.penggajian.entity.TunjanganYayasan;
import com.penggajian.main.DialogView;
import com.penggajian.main.MainView;
import com.penggajian.main.SpringManager;
import com.penggajian.service.MasterService;
import com.penggajian.util.TextComponentUtils;
import com.stripbandunk.jglasspane.component.MessageComponent;
import com.stripbandunk.jwidget.JDynamicTable;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import java.awt.Window;
import java.math.BigDecimal;
import org.springframework.dao.DataAccessException;

/**
 *
 * @author Windows
 */
public class SetupTunjanganPegawaiDialog extends DialogView {

    /**
     * Creates new form TambahTransaksiPenggajianDialog
     */
    private TransaksiPenggajianPegawai tpp;
    private DetailPerincianHonor dph;
    private MasterPegawai mpg;
    //private TambahTransaksiPenggajianDialog dialog;
    
    private JDynamicTable dynamicTable;
    private DynamicTableModel<DetailPerincianHonor> dynamicTableModel;
    private MessageComponent messageComponent;
    
    
    public SetupTunjanganPegawaiDialog(MainView mainView) {
        super(mainView);
        initComponents();
        jTabbedPane2.remove(jPanel1);
        jTabbedPane2.remove(jPanel2);
        jTabbedPane2.remove(jPanel3);
        jTabbedPane2.remove(jPanel4);
        //jTabbedPane2.remove(jPanel5);
        jTabbedPane2.remove(jPanel6);
        
    }
   
    public TransaksiPenggajianPegawai search(Window formApp) {
        display(formApp, null);
        return tpp;
    }
    public DetailPerincianHonor searchDPH(Window formApp) {
        display(formApp, null);
        return dph;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNIP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtStatusKepegawaian = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPokokHonor = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        cmbJumlahRombel = new javax.swing.JComboBox();
        jLabel48 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtJumlahTunjanganStafKurikulum = new javax.swing.JTextField();
        txtJumlahTunjanganStafKesiswaan = new javax.swing.JTextField();
        txtJumlahTunjanganStafSaranaDanPrasarana = new javax.swing.JTextField();
        txtJumlahTunjanganStafHumas = new javax.swing.JTextField();
        txtJumlahTunjanganStafWaliKelas = new javax.swing.JTextField();
        cmbJumlahJamTunjanganStafKurikulum = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        cmbJumlahJamTunjanganStafKesiswaan = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganStafSaranaDanPrasarana = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganStafHumas = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganStafWaliKelas = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtJumlahTunjanganEkstraKurikuluerOR = new javax.swing.JTextField();
        txtJumlahTunjanganEkstraKurikuluerSeni = new javax.swing.JTextField();
        txtJumlahTunjanganEkstraKurikuluerPraPMR = new javax.swing.JTextField();
        txtJumlahTunjanganEkstraKurikuluerUKS = new javax.swing.JTextField();
        txtJumlahTunjanganEkstraKurikuluerPasti = new javax.swing.JTextField();
        cmbJumlahJamTunjanganEkstraKurikuluerOR = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganEkstraKurikuluerSeni = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganEkstraKurikuluerPraPMR = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganEkstraKurikuluerUKS = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganEkstraKurikuluerPasti = new javax.swing.JComboBox();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtJumlahTunjanganKurikulerPengabdian = new javax.swing.JTextField();
        txtJumlahTunjanganKurikulerBP = new javax.swing.JTextField();
        txtJumlahTunjanganKurikulerPraktikum = new javax.swing.JTextField();
        txtJumlahTunjanganKurikulerKomputer = new javax.swing.JTextField();
        cmbJumlahJamTunjanganKurikulerPengabdian = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganKurikulerBP = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganKurikulerPraktikum = new javax.swing.JComboBox();
        cmbJumlahJamTunjanganKurikulerKomputer = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        cmbJumlahJamTunjanganKurikulerPembinaOSIS = new javax.swing.JComboBox();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtJumlahTunjanganKurikulerPembinaOSIS = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtKabid = new javax.swing.JTextField();
        txtStaf = new javax.swing.JTextField();
        txtSatpam = new javax.swing.JTextField();
        txtPegawaiKebersihan = new javax.swing.JTextField();
        txtTransport = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPokokHonorYayasan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setup Perincian Honor Pegawai");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SETUP PERINCIAN HONOR PEGAWAI");

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("NIP");

        jLabel3.setText("Nama");

        jLabel5.setText("Status Kepegawaian");

        jLabel6.setText("Jumlah Jam Mengajar");

        jLabel7.setText("KJM");

        jLabel8.setText("Pokok Honor");

        jLabel9.setText("Jumlah KJM");

        txtNama.setEnabled(false);

        txtStatusKepegawaian.setEnabled(false);

        jLabel10.setText("Jam.");

        jLabel11.setText("Jam");

        txtPokokHonor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPokokHonor.setEnabled(false);

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setEnabled(false);

        btnCari.setText("...");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtStatusKepegawaian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(txtPokokHonor, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStatusKepegawaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPokokHonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Data Pegawai", jPanel1);

        jLabel46.setText("Jumlah Rombongan Belajar");

        txtJumlah.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlah.setEnabled(false);

        jLabel47.setText("Rombel");

        cmbJumlahRombel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Salah Satu --", "2 - 6", "7 - 10", "11 - 14", "15 - 18", "19 - 22", "23 - Lebih" }));
        cmbJumlahRombel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        jLabel48.setText("Jumlah");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbJumlahRombel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47))
                    .addComponent(txtJumlah))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(cmbJumlahRombel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tunjangan Jabatan", jPanel6);

        jLabel12.setText("Kurikulum");

        jLabel13.setText("Kesiswaan");

        jLabel14.setText("Sarana/Prasarana");

        jLabel15.setText("Humas");

        jLabel16.setText("Wali Kelas");

        txtJumlahTunjanganStafKurikulum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganStafKurikulum.setText("0");
        txtJumlahTunjanganStafKurikulum.setEnabled(false);

        txtJumlahTunjanganStafKesiswaan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganStafKesiswaan.setText("0");
        txtJumlahTunjanganStafKesiswaan.setEnabled(false);

        txtJumlahTunjanganStafSaranaDanPrasarana.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganStafSaranaDanPrasarana.setText("0");
        txtJumlahTunjanganStafSaranaDanPrasarana.setEnabled(false);

        txtJumlahTunjanganStafHumas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganStafHumas.setText("0");
        txtJumlahTunjanganStafHumas.setEnabled(false);

        txtJumlahTunjanganStafWaliKelas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganStafWaliKelas.setText("0");
        txtJumlahTunjanganStafWaliKelas.setEnabled(false);

        cmbJumlahJamTunjanganStafKurikulum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganStafKurikulum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        jLabel32.setText("Jumlah");

        cmbJumlahJamTunjanganStafKesiswaan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganStafKesiswaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        cmbJumlahJamTunjanganStafSaranaDanPrasarana.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganStafSaranaDanPrasarana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        cmbJumlahJamTunjanganStafHumas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganStafHumas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        cmbJumlahJamTunjanganStafWaliKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganStafWaliKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        jLabel37.setText("Jumlah");

        jLabel38.setText("Jumlah");

        jLabel39.setText("Jumlah");

        jLabel40.setText("Jumlah");

        jLabel55.setText("Jam");

        jLabel56.setText("Jam");

        jLabel57.setText("Jam");

        jLabel58.setText("Jam");

        jLabel59.setText("Jam");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbJumlahJamTunjanganStafHumas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganStafSaranaDanPrasarana, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganStafKurikulum, javax.swing.GroupLayout.Alignment.LEADING, 0, 73, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganStafKesiswaan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganStafWaliKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel55)
                        .addGap(18, 39, Short.MAX_VALUE)
                        .addComponent(jLabel32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel38))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJumlahTunjanganStafKurikulum, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJumlahTunjanganStafSaranaDanPrasarana)
                            .addComponent(txtJumlahTunjanganStafHumas)
                            .addComponent(txtJumlahTunjanganStafWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtJumlahTunjanganStafKesiswaan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtJumlahTunjanganStafKurikulum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganStafKurikulum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtJumlahTunjanganStafKesiswaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganStafKesiswaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel56))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtJumlahTunjanganStafSaranaDanPrasarana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganStafSaranaDanPrasarana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtJumlahTunjanganStafHumas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganStafHumas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtJumlahTunjanganStafWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganStafWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel59))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tunjangan Staf", jPanel2);

        jLabel21.setText("OR");

        jLabel22.setText("Seni");

        jLabel23.setText("Pra/PMR");

        jLabel24.setText("UKS");

        jLabel25.setText("Pasti");

        txtJumlahTunjanganEkstraKurikuluerOR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganEkstraKurikuluerOR.setText("0");
        txtJumlahTunjanganEkstraKurikuluerOR.setEnabled(false);

        txtJumlahTunjanganEkstraKurikuluerSeni.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganEkstraKurikuluerSeni.setText("0");
        txtJumlahTunjanganEkstraKurikuluerSeni.setEnabled(false);

        txtJumlahTunjanganEkstraKurikuluerPraPMR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganEkstraKurikuluerPraPMR.setText("0");
        txtJumlahTunjanganEkstraKurikuluerPraPMR.setEnabled(false);

        txtJumlahTunjanganEkstraKurikuluerUKS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganEkstraKurikuluerUKS.setText("0");
        txtJumlahTunjanganEkstraKurikuluerUKS.setEnabled(false);

        txtJumlahTunjanganEkstraKurikuluerPasti.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganEkstraKurikuluerPasti.setText("0");
        txtJumlahTunjanganEkstraKurikuluerPasti.setEnabled(false);

        cmbJumlahJamTunjanganEkstraKurikuluerOR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));

        cmbJumlahJamTunjanganEkstraKurikuluerSeni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));

        cmbJumlahJamTunjanganEkstraKurikuluerPraPMR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));

        cmbJumlahJamTunjanganEkstraKurikuluerUKS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));

        cmbJumlahJamTunjanganEkstraKurikuluerPasti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));

        jLabel49.setText("Jumlah");

        jLabel50.setText("Jumlah");

        jLabel51.setText("Jumlah");

        jLabel52.setText("Jumlah");

        jLabel53.setText("Jumlah");

        jLabel64.setText("Jam");

        jLabel65.setText("Jam");

        jLabel66.setText("Jam");

        jLabel67.setText("Jam");

        jLabel68.setText("Jam");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerOR, 0, 73, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerSeni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerPraPMR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerUKS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerPasti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel68)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel53))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel67)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel52))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel66)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel51))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel50))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel64)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel49)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerOR, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerSeni)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerPraPMR)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerUKS)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerPasti))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(jLabel64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerSeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerSeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(jLabel65))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerPraPMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerPraPMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel66))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerUKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerUKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtJumlahTunjanganEkstraKurikuluerPasti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganEkstraKurikuluerPasti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(jLabel68))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tunjangan Ekstrakurikuluer", jPanel4);

        jLabel17.setText("Pengabdian");

        jLabel18.setText("BP");

        jLabel19.setText("Praktikum");

        jLabel20.setText("Komp/Mycc");

        txtJumlahTunjanganKurikulerPengabdian.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganKurikulerPengabdian.setText("0");
        txtJumlahTunjanganKurikulerPengabdian.setEnabled(false);

        txtJumlahTunjanganKurikulerBP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganKurikulerBP.setText("0");
        txtJumlahTunjanganKurikulerBP.setEnabled(false);

        txtJumlahTunjanganKurikulerPraktikum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganKurikulerPraktikum.setText("0");
        txtJumlahTunjanganKurikulerPraktikum.setEnabled(false);

        txtJumlahTunjanganKurikulerKomputer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganKurikulerKomputer.setText("0");
        txtJumlahTunjanganKurikulerKomputer.setEnabled(false);

        cmbJumlahJamTunjanganKurikulerPengabdian.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganKurikulerPengabdian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        cmbJumlahJamTunjanganKurikulerBP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganKurikulerBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        cmbJumlahJamTunjanganKurikulerPraktikum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganKurikulerPraktikum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        cmbJumlahJamTunjanganKurikulerKomputer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganKurikulerKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        jLabel33.setText("Jumlah");

        jLabel34.setText("Jumlah");

        jLabel35.setText("Jumlah");

        jLabel36.setText("Jumlah");

        jLabel60.setText("Jam");

        jLabel61.setText("Jam");

        jLabel62.setText("Jam");

        jLabel63.setText("Jam");

        jLabel70.setText("Pembina OSIS");

        cmbJumlahJamTunjanganKurikulerPembinaOSIS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih --", "3", "4", "6" }));
        cmbJumlahJamTunjanganKurikulerPembinaOSIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction(evt);
            }
        });

        jLabel71.setText("Jam");

        jLabel72.setText("Jumlah");

        txtJumlahTunjanganKurikulerPembinaOSIS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahTunjanganKurikulerPembinaOSIS.setText("0");
        txtJumlahTunjanganKurikulerPembinaOSIS.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel70)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbJumlahJamTunjanganKurikulerBP, 0, 73, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganKurikulerPraktikum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganKurikulerKomputer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganKurikulerPengabdian, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbJumlahJamTunjanganKurikulerPembinaOSIS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJumlahTunjanganKurikulerBP)
                            .addComponent(txtJumlahTunjanganKurikulerPraktikum)
                            .addComponent(txtJumlahTunjanganKurikulerKomputer)
                            .addComponent(txtJumlahTunjanganKurikulerPengabdian, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel71)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtJumlahTunjanganKurikulerPembinaOSIS)))
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel70)
                            .addComponent(cmbJumlahJamTunjanganKurikulerPembinaOSIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71)
                            .addComponent(jLabel72)
                            .addComponent(txtJumlahTunjanganKurikulerPembinaOSIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtJumlahTunjanganKurikulerPengabdian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJumlahJamTunjanganKurikulerPengabdian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel60))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtJumlahTunjanganKurikulerBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJumlahJamTunjanganKurikulerBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel61)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtJumlahTunjanganKurikulerPraktikum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganKurikulerPraktikum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtJumlahTunjanganKurikulerKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJumlahJamTunjanganKurikulerKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel63))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tunjangan Kurikuler", jPanel3);

        jLabel27.setText("Kepala Bidang");

        jLabel28.setText("Staf");

        jLabel29.setText("Satpam");

        jLabel30.setText("Pegawai Kebersihan");

        jLabel31.setText("Transport");

        txtKabid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKabid.setText("0");
        txtKabid.setEnabled(false);

        txtStaf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtStaf.setText("0");
        txtStaf.setEnabled(false);

        txtSatpam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSatpam.setText("0");
        txtSatpam.setEnabled(false);

        txtPegawaiKebersihan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPegawaiKebersihan.setText("0");
        txtPegawaiKebersihan.setEnabled(false);

        txtTransport.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTransport.setText("0");

        jLabel26.setText("Pokok Honor");

        txtPokokHonorYayasan.setEditable(false);
        txtPokokHonorYayasan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPokokHonorYayasan.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKabid)
                    .addComponent(txtStaf)
                    .addComponent(txtSatpam)
                    .addComponent(txtPegawaiKebersihan)
                    .addComponent(txtTransport, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtPokokHonorYayasan))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtKabid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtStaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtSatpam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtPegawaiKebersihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtTransport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtPokokHonorYayasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Tunjangan Yayasan", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Tambah, btnBatal});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah)
                    .addComponent(btnBatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction
        // TODO add your handling code here:
        Object source = evt.getSource();
        BigDecimal tunjangan, pokokHonor;
        if (source == Tambah) {
            dph = new DetailPerincianHonor();
            //System.out.println("Staf : "+TambahTransaksiPenggajianDialog.getSatpam());
            /*dph.setTunjanganStaf(TambahTransaksiPenggajianDialog.getStaf());
            dph.setTunjanganSatpam(TambahTransaksiPenggajianDialog.getSatpam());
            dph.setTunjanganPegawaiKebersihan(TambahTransaksiPenggajianDialog.getKebersihan());
            dph.setTunjanganKepalaBidang(TambahTransaksiPenggajianDialog.getBidang());
            dph.setTunjanganTransport(BigDecimal.valueOf(Long.valueOf(txtTransport.getText().replace(".", "").trim())));
            dph.setPokokHonor(BigDecimal.valueOf(Long.valueOf(txtPokokHonorYayasan.getText().replace(".", "").trim())));
            dph.setJumlahHonor(BigDecimal.valueOf(Long.valueOf(txtStaf.getText().replace(".", "").trim()))
                    .add(BigDecimal.valueOf(Long.valueOf(txtSatpam.getText().replace(".", "").trim())))
                    .add(BigDecimal.valueOf(Long.valueOf(txtPegawaiKebersihan.getText().replace(".", "").trim())))
                            .add(BigDecimal.valueOf(Long.valueOf(txtKabid.getText().replace(".", "").trim())))
                    .add(BigDecimal.valueOf(Long.valueOf(txtPokokHonorYayasan.getText().replace(".", "").trim())))
                    .add(BigDecimal.valueOf(Long.valueOf(txtTransport.getText().replace(".", "").trim()))));*/
            dph.setTunjanganStaf(BigDecimal.valueOf(Long.valueOf(txtStaf.getText().replace(".", "").trim())));
            dph.setTunjanganSatpam(BigDecimal.valueOf(Long.valueOf(txtSatpam.getText().replace(".", "").trim())));
            dph.setTunjanganPegawaiKebersihan(BigDecimal.valueOf(Long.valueOf(txtPegawaiKebersihan.getText().replace(".", "").trim())));
            dph.setTunjanganKepalaBidang(BigDecimal.valueOf(Long.valueOf(txtKabid.getText().replace(".", "").trim())));
            dph.setTunjanganTransport(BigDecimal.valueOf(Long.valueOf(txtTransport.getText().replace(".", "").trim())));
            dph.setPokokHonor(BigDecimal.valueOf(Long.valueOf(txtPokokHonorYayasan.getText().replace(".", "").trim())));
            dph.setJumlahHonor(BigDecimal.valueOf(Long.valueOf(txtStaf.getText().replace(".", "").trim()))
                    .add(BigDecimal.valueOf(Long.valueOf(txtSatpam.getText().replace(".", "").trim())))
                    .add(BigDecimal.valueOf(Long.valueOf(txtPegawaiKebersihan.getText().replace(".", "").trim())))
                            .add(BigDecimal.valueOf(Long.valueOf(txtKabid.getText().replace(".", "").trim())))
                    .add(BigDecimal.valueOf(Long.valueOf(txtPokokHonorYayasan.getText().replace(".", "").trim())))
                    .add(BigDecimal.valueOf(Long.valueOf(txtTransport.getText().replace(".", "").trim()))));
            
            dispose();
            
            /*MasterService masterService = SpringManager.getInstance().getBean(MasterService.class);
            
            try {
                //validator.validate(mp);
                masterService.save(dph);
                dispose();
            } catch (DataAccessException e) {
                showError(e.getRootCause().getMessage());
            //} catch (ValidatorException ex) {
                //showWarning(ex.getMessage());
            }*/
            
        } else if (source == btnCari){
            CariPegawaiView cariPegawai = new CariPegawaiView(getMainView());
            mpg = cariPegawai.search(this);
            if (mpg != null) {
                txtNIP.setText(mpg.getNip());
                txtNama.setText(mpg.getNama());
                txtStatusKepegawaian.setText(mpg.getStatusKepegawaian());
                
                pokokHonor = hitungPokokHonor(mpg.getStatusKepegawaian(), mpg.getSubstatusKepegawaian(), mpg.getPendidikan());
                txtPokokHonor.setText(String.valueOf(pokokHonor));
            }
        } else if(source == cmbJumlahRombel) {
            if (mpg != null) {
                if (mpg.getJabatan().equals("Kepala TK")) {
                    tunjangan = hitungTunjanganJabatan(mpg.getJabatan(), mpg.getGolongan(), cmbJumlahRombel.getSelectedItem().toString().trim());
                    txtJumlah.setText(String.valueOf(tunjangan));
                    //System.out.println("Tes Kepala TK : "+mpg.getJabatan());
                } else {
                    tunjangan = hitungTunjanganJabatan(mpg.getJabatan().substring(0, 6).trim() +" "+ mpg.getUnitKerja().trim(), mpg.getGolongan(), cmbJumlahRombel.getSelectedItem().toString().trim());
                    txtJumlah.setText(String.valueOf(tunjangan));
                    //System.out.println("Tes : "+mpg.getJabatan().substring(0, 6).trim() +" "+ mpg.getUnitKerja().trim());
                }
            }
        //Tunjangan Staf
        } else if(source == cmbJumlahJamTunjanganStafKurikulum) {
            if (mpg != null) {
                txtJumlahTunjanganStafKurikulum.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Staf Kasi Kurikulum", mpg.getUnitKerja(), cmbJumlahJamTunjanganStafKurikulum.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganStafKesiswaan) {
            if (mpg != null) {
                txtJumlahTunjanganStafKesiswaan.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Staf Kasi Kesiswaan", mpg.getUnitKerja(), cmbJumlahJamTunjanganStafKesiswaan.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganStafSaranaDanPrasarana) {
            if (mpg != null) {
                txtJumlahTunjanganStafSaranaDanPrasarana.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Staf Kasi Sarana/Prasarana", mpg.getUnitKerja(), cmbJumlahJamTunjanganStafSaranaDanPrasarana.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganStafHumas) {
            if (mpg != null) {
                txtJumlahTunjanganStafHumas.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Staf Kasi Humas", mpg.getUnitKerja(), cmbJumlahJamTunjanganStafHumas.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganStafWaliKelas) {
            if (mpg != null) {
                txtJumlahTunjanganStafWaliKelas.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Staf Wali Kelas", mpg.getUnitKerja(), cmbJumlahJamTunjanganStafWaliKelas.getSelectedItem().toString().trim())));
            }  
        //Tunjangan Kurikuler
        } else if(source == cmbJumlahJamTunjanganKurikulerPembinaOSIS) {
            if (mpg != null) {
                txtJumlahTunjanganKurikulerPembinaOSIS.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Kurikuler Pembina OSIS", mpg.getUnitKerja(), cmbJumlahJamTunjanganKurikulerPembinaOSIS.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganKurikulerBP) {
            if (mpg != null) {
                txtJumlahTunjanganKurikulerBP.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Kurikuler BP", mpg.getUnitKerja(), cmbJumlahJamTunjanganKurikulerBP.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganKurikulerPraktikum) {
            if (mpg != null) {
                txtJumlahTunjanganKurikulerPraktikum.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Kurikulum Praktikum", mpg.getUnitKerja(), cmbJumlahJamTunjanganKurikulerPraktikum.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganKurikulerKomputer) {
            if (mpg != null) {
                txtJumlahTunjanganKurikulerKomputer.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("", mpg.getUnitKerja(), cmbJumlahJamTunjanganKurikulerKomputer.getSelectedItem().toString().trim())));
            }
        
        //Tunjangan Ekstrakurikuluer
        } else if(source == cmbJumlahJamTunjanganEkstraKurikuluerOR) {
            if (mpg != null) {
                txtJumlahTunjanganEkstraKurikuluerOR.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Ekstra OR", mpg.getUnitKerja(), cmbJumlahJamTunjanganEkstraKurikuluerOR.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganEkstraKurikuluerSeni) {
            if (mpg != null) {
                txtJumlahTunjanganEkstraKurikuluerSeni.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Ekstra Seni", mpg.getUnitKerja(), cmbJumlahJamTunjanganEkstraKurikuluerSeni.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganEkstraKurikuluerPraPMR) {
            if (mpg != null) {
                txtJumlahTunjanganEkstraKurikuluerPraPMR.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Ekstra Pra/PMR", mpg.getUnitKerja(), cmbJumlahJamTunjanganEkstraKurikuluerPraPMR.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganEkstraKurikuluerUKS) {
            if (mpg != null) {
                txtJumlahTunjanganEkstraKurikuluerUKS.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan UKS", mpg.getUnitKerja(), cmbJumlahJamTunjanganEkstraKurikuluerUKS.getSelectedItem().toString().trim())));
            }
        } else if(source == cmbJumlahJamTunjanganEkstraKurikuluerPasti) {
            if (mpg != null) {
                txtJumlahTunjanganEkstraKurikuluerPasti.setText(String.valueOf(hitungTunjanganStaffKurikulumEkstraKurikuluer("Tunjangan Pasti", mpg.getUnitKerja(), cmbJumlahJamTunjanganEkstraKurikuluerPasti.getSelectedItem().toString().trim())));
            }
        } else if(source == btnBatal) {
            dispose();
        }
    }//GEN-LAST:event_buttonAction

    private BigDecimal hitungTunjanganJabatan(String jabatanPegawai, String golPegawa, String jumlahRombel){           
        BigDecimal tunjangan = BigDecimal.ZERO;
        
        MasterService masterService = SpringManager.getInstance().getBean(MasterService.class);
        for (TabelTunjanganJabatan tj : masterService.getAllTunjanganJabatan()) {
            if (jabatanPegawai.equals(tj.getJabatan()) && golPegawa.equals(tj.getGolongan()) && jumlahRombel.equals(tj.getJumlahRombengan())) {
                tunjangan = tj.getJumlahTunjangan();
            }else if (jabatanPegawai.equals(tj.getJabatan()) && golPegawa.equals(tj.getGolongan()) && jumlahRombel.equals(tj.getJumlahRombengan())) {
                tunjangan = tj.getJumlahTunjangan();
            }
        }
        //System.out.println("Tess  "+tunjangan);
        return tunjangan;
    }
    
    private BigDecimal hitungPokokHonor(String statusKepeg, String subStatusKepeg, String pendidikan){           
        BigDecimal pokokHonor = BigDecimal.ZERO;
        
        MasterService masterService = SpringManager.getInstance().getBean(MasterService.class);
        for (PokokHonor ph : masterService.getAllPokokHonor()) {
            if (statusKepeg.equals(ph.getStatusKepegawaian()) && !subStatusKepeg.equals(ph.getSubStatusKepegawaian()) && pendidikan.equals(ph.getPendidikan())) {
                pokokHonor = ph.getJumlah();
            } else if (statusKepeg.equals(ph.getStatusKepegawaian()) && subStatusKepeg.equals(ph.getSubStatusKepegawaian()) && pendidikan.equals(ph.getPendidikan())) {
                pokokHonor = ph.getJumlah();
            }
        }
        //System.out.println("Tess PH: "+pokokHonor);
        return pokokHonor;
    }
    
    private BigDecimal hitungTunjanganStaffKurikulumEkstraKurikuluer(String jenisTunjangan, String unitKerja, String jumlahJam){           
        BigDecimal pokokHonor = BigDecimal.ZERO;
        BigDecimal ph; 
        
        MasterService masterService = SpringManager.getInstance().getBean(MasterService.class);
        for (TunjanganStaffKurikulumEkstrakurikuluer ts : masterService.getAllTunjanganStaffKurikulumKasi()) {
            if (jenisTunjangan.equals(ts.getJenisTunjangan()) && unitKerja.equals(ts.getUnitKerja()) && jumlahJam.equals(ts.getJumlahJam())) {
                ph = ts.getJumlahTunjangan().multiply(BigDecimal.valueOf(Long.valueOf(ts.getJumlahJam())));
                pokokHonor = ph;
            }
        }
        //System.out.println("Tess PH: "+pokokHonor);
        return pokokHonor;
    }
    
    private BigDecimal hitungRincianHonorYayasan(String jabatanPegawai, String golPegawa, String jenisTunjangan){           
        BigDecimal tunjangan = BigDecimal.ZERO;
        
        MasterService masterService = SpringManager.getInstance().getBean(MasterService.class);
        for (TunjanganYayasan ty : masterService.getAllTunjanganYayasan()) {
            if (jabatanPegawai.equals(ty.getJabatan()) && golPegawa.equals(ty.getGolongan()) && jenisTunjangan.equals(ty.getJenisTunjangan())) {
                tunjangan = ty.getBesarTunjangan();
                //System.out.println("= "+tunjangan);
            }else if (!jenisTunjangan.equals("Khusus")) {
                tunjangan = BigDecimal.ZERO;
            }
        }
        //System.out.println("Tess  "+tunjangan);
        return tunjangan;
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiPenggajianDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiPenggajianDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiPenggajianDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiPenggajianDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TambahTransaksiPenggajianDialog dialog = new TambahTransaksiPenggajianDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tambah;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JComboBox cmbJumlahJamTunjanganEkstraKurikuluerOR;
    private javax.swing.JComboBox cmbJumlahJamTunjanganEkstraKurikuluerPasti;
    private javax.swing.JComboBox cmbJumlahJamTunjanganEkstraKurikuluerPraPMR;
    private javax.swing.JComboBox cmbJumlahJamTunjanganEkstraKurikuluerSeni;
    private javax.swing.JComboBox cmbJumlahJamTunjanganEkstraKurikuluerUKS;
    private javax.swing.JComboBox cmbJumlahJamTunjanganKurikulerBP;
    private javax.swing.JComboBox cmbJumlahJamTunjanganKurikulerKomputer;
    private javax.swing.JComboBox cmbJumlahJamTunjanganKurikulerPembinaOSIS;
    private javax.swing.JComboBox cmbJumlahJamTunjanganKurikulerPengabdian;
    private javax.swing.JComboBox cmbJumlahJamTunjanganKurikulerPraktikum;
    private javax.swing.JComboBox cmbJumlahJamTunjanganStafHumas;
    private javax.swing.JComboBox cmbJumlahJamTunjanganStafKesiswaan;
    private javax.swing.JComboBox cmbJumlahJamTunjanganStafKurikulum;
    private javax.swing.JComboBox cmbJumlahJamTunjanganStafSaranaDanPrasarana;
    private javax.swing.JComboBox cmbJumlahJamTunjanganStafWaliKelas;
    private javax.swing.JComboBox cmbJumlahRombel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtJumlahTunjanganEkstraKurikuluerOR;
    private javax.swing.JTextField txtJumlahTunjanganEkstraKurikuluerPasti;
    private javax.swing.JTextField txtJumlahTunjanganEkstraKurikuluerPraPMR;
    private javax.swing.JTextField txtJumlahTunjanganEkstraKurikuluerSeni;
    private javax.swing.JTextField txtJumlahTunjanganEkstraKurikuluerUKS;
    private javax.swing.JTextField txtJumlahTunjanganKurikulerBP;
    private javax.swing.JTextField txtJumlahTunjanganKurikulerKomputer;
    private javax.swing.JTextField txtJumlahTunjanganKurikulerPembinaOSIS;
    private javax.swing.JTextField txtJumlahTunjanganKurikulerPengabdian;
    private javax.swing.JTextField txtJumlahTunjanganKurikulerPraktikum;
    private javax.swing.JTextField txtJumlahTunjanganStafHumas;
    private javax.swing.JTextField txtJumlahTunjanganStafKesiswaan;
    private javax.swing.JTextField txtJumlahTunjanganStafKurikulum;
    private javax.swing.JTextField txtJumlahTunjanganStafSaranaDanPrasarana;
    private javax.swing.JTextField txtJumlahTunjanganStafWaliKelas;
    private javax.swing.JTextField txtKabid;
    private javax.swing.JTextField txtNIP;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPegawaiKebersihan;
    private javax.swing.JTextField txtPokokHonor;
    private javax.swing.JTextField txtPokokHonorYayasan;
    private javax.swing.JTextField txtSatpam;
    private javax.swing.JTextField txtStaf;
    private javax.swing.JTextField txtStatusKepegawaian;
    private javax.swing.JTextField txtTransport;
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(Window formApp, Object parameter) {
        //mpg = (MasterPegawai) parameter;
        //if (mpg!=null) {
            /*if (mpg.getJabatan().equals("Kepala Bidang")) {
                txtKabid.setText(TextComponentUtils.formatNumber(hitungRincianHonorYayasan(mpg.getJabatan(), mpg.getGolongan(), "Khusus")));
            }
            if (mpg.getJabatan().equals("Staf")){
                txtStaf.setText(TextComponentUtils.formatNumber(hitungRincianHonorYayasan(mpg.getJabatan(), mpg.getGolongan(), "Khusus")));
            }
            if (mpg.getJabatan().equals("Satpam")) {
                txtSatpam.setText(TextComponentUtils.formatNumber(hitungRincianHonorYayasan(mpg.getJabatan(), mpg.getGolongan(), "Khusus")));
            }
            if (mpg.getJabatan().equals("Pegawai Kebersihan")) {
                txtPegawaiKebersihan.setText(TextComponentUtils.formatNumber(hitungRincianHonorYayasan(mpg.getJabatan(), mpg.getGolongan(), "Khusus")));
            }
            
                txtPokokHonorYayasan.setText(TextComponentUtils.formatNumber(hitungPokokHonor(mpg.getStatusKepegawaian(), mpg.getSubstatusKepegawaian(), mpg.getPendidikan())));
        //}*/
        TextComponentUtils.setCurrency(txtPokokHonorYayasan);
        TextComponentUtils.setCurrency(txtTransport);
        txtKabid.setText(TextComponentUtils.formatNumber(TambahTransaksiPenggajianDialog.getBidang()));
        System.out.println("Bidang : "+TambahTransaksiPenggajianDialog.getBidang());
        txtStaf.setText(TextComponentUtils.formatNumber(TambahTransaksiPenggajianDialog.getStaf()));
        System.out.println("Staf : "+TambahTransaksiPenggajianDialog.getStaf());
        txtSatpam.setText(TextComponentUtils.formatNumber(TambahTransaksiPenggajianDialog.getSatpam()));
        System.out.println("Satpam : "+TambahTransaksiPenggajianDialog.getSatpam());
        txtPegawaiKebersihan.setText(TextComponentUtils.formatNumber(TambahTransaksiPenggajianDialog.getKebersihan()));
        System.out.println("Peg. Keber : "+TambahTransaksiPenggajianDialog.getKebersihan());
                
        txtPokokHonorYayasan.setText(TextComponentUtils.formatNumber(TambahTransaksiPenggajianDialog.getPokokHonor()));
        System.out.println("Pokok Honor : "+TambahTransaksiPenggajianDialog.getPokokHonor());
        setLocationRelativeTo(formApp);
        setVisible(true);
        
    }
}
